PATCH  http://localhost:3000/produtos/2 HTTP/1.1
content-type: application/json
 
{
    "produto": "Radeon",
    "preco": "2000",
    "condicao": "Usado",
    "marca": "Gigabyte",
    "descricao": "Muito cara",
    "data": "13/10/2022"
}