POST http://localhost:3000/atendimentos HTTP/1.1
content-type: application/json
 
{
    "produto": "Maria",
    "preço": "RTX 3090",
    "condição": "Check-up",
    "marca": "Agendado",
    "descrição": "",
    "data": "13/10/2022"
}
