POST http://localhost:3000/produtos HTTP/1.1
content-type: application/json

{
    "produto": "kkkkk",
    "preco": "k",
    "condicao": "k",
    "marca": "k",
    "descricao": "k",
    "imagem": "https://i.ebayimg.com/images/g/D3QAAOSw9gJf6c55/s-l600.jpg"
}
